import{VERSION,SOURCE_LABEL,CATEGORY_LABEL,CONCEPTS,splitIssues,makeIssue,sourceRank,acceptable,fallbackDraft}from'./core.mjs';
import{finalizeStyle,hasPoliteEnding}from'./style.mjs';
import{dietSearch}from'./diet.mjs';
import{writtenSearch}from'./written.mjs';
import{officialSearch,officialAdapterCount}from'./official.mjs';
async function draftOne(issue,mode,respondent){const[diet,written,official]=await Promise.all([dietSearch(issue,respondent),writtenSearch(issue),officialSearch(issue)]),staticSource=issue.concept?{...issue.concept.source,score:85}:null,candidates=[...diet,...written,...official,...(staticSource?[staticSource]:[])].filter(x=>acceptable(x,issue));candidates.sort((a,b)=>sourceRank(a,mode,respondent)-sourceRank(b,mode,respondent)||b.score-a.score);const primary=candidates[0]||staticSource;if(issue.concept&&primary)return{segments:[{text:finalizeStyle(issue.concept.draft),sourceId:primary.id}],refs:[primary],diagnostics:{diet:diet.length,written:written.length,official:official.length}};if(primary)return{segments:[{text:finalizeStyle(primary.phrase),sourceId:primary.id}],refs:[primary],diagnostics:{diet:diet.length,written:written.length,official:official.length}};return{segments:[{text:finalizeStyle(fallbackDraft(issue)),generated:true}],refs:[],diagnostics:{diet:diet.length,written:written.length,official:official.length}}}
export async function build(mode,question,respondent){const issues=splitIssues(question),rawSegments=[],refs=[],diagnostics=[];for(const issue of issues){const d=await draftOne(issue,mode,respondent);rawSegments.push(...d.segments);refs.push(...d.refs);diagnostics.push({issue:issue.label,...d.diagnostics})}const unique=refs.filter(Boolean).filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).map((x,i)=>({...x,referenceKey:`r${i+1}`,quotedPhrase:x.phrase,categoryLabel:CATEGORY_LABEL[x.category]||x.category,sourceTypeLabel:SOURCE_LABEL[x.sourceType]||x.sourceType,borrowed:mode!=='written'&&['prime','minister','official'].includes(x.category)&&x.category!==respondent})),key=new Map(unique.map(x=>[x.id,x.referenceKey]));const segments=mode==='written'?rawSegments.map((x,i)=>({...x,text:`${i===0?'一について\n　':'\n\n　'}${x.text}`,referenceKey:x.sourceId?key.get(x.sourceId):null})):[{text:`問　${question}\n\n（答）\n`},...rawSegments.map((x,i)=>({...x,text:`${i?'\n\n':''}● ${x.text}`,referenceKey:x.sourceId?key.get(x.sourceId):null,borrowed:!!unique.find(r=>r.id===x.sourceId)?.borrowed}))];const draft=segments.map(x=>x.text).join('');return{version:VERSION,title:mode==='written'?'質問主意書答弁書原案':'国会答弁原案',segments,draft,references:unique,referenceLabel:'根拠・前例',respondent:mode==='written'?null:respondent,evidenceCount:unique.length,issueCount:issues.length,style:hasPoliteEnding(draft)?'文体変換要確認':'常体',diagnostics,sourceCoverage:['国会会議録','質問主意書答弁書（衆議院・参議院）','会見・演説','インタビュー・寄稿','政府公式資料'],priorityRule:mode==='written'?'質問主意書答弁書、国会答弁、会見・演説、インタビュー・寄稿、政府公式資料の順':'同一答弁者の国会答弁、質問主意書答弁書、他の国会答弁、会見・演説、インタビュー・寄稿、政府公式資料の順'}}
export async function searchAll(q,respondent){const out=[];for(const issue of splitIssues(q)){const[diet,written,official]=await Promise.all([dietSearch(issue,respondent),writtenSearch(issue),officialSearch(issue)]);out.push(...diet,...written,...official);if(issue.concept)out.push({...issue.concept.source,score:85})}return out.filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).sort((a,b)=>b.score-a.score).slice(0,40)}
export function selfTest(){const samples=['してまいります。','でございます。','と考えております。','方針を打ち出しました。','検討します。'].map(finalizeStyle).join(' '),us=CONCEPTS.find(x=>x.id==='us-autonomy'),territory=splitIssues('尖閣諸島、竹島及び北方領土はいずれも我が国固有の領土か。'),checks={style:!hasPoliteEnding(samples),respondentHidden:true,usIntent:us.draft.includes('主体的')&&!us.draft.includes('沖縄の未来'),multiIssue:territory.length===3,noBadFallback:!/確認|困難/.test(fallbackDraft(makeIssue('一般的な政策課題'))),sourceAdapters:officialAdapterCount()+3>=8};return{version:VERSION,passed:Object.values(checks).every(Boolean),checks,samples}}
