const json=(res,status,body)=>{res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body));};
const clean=s=>String(s||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const LABEL={prime:'総理',minister:'大臣',official:'政府参考人',cabinet:'閣議決定済み答弁書',conference:'会見・演説',official_policy:'政府公式資料',treaty:'条約・国際文書'};
const PRIORITY={answer:1,conference:2,fact:3};
const STOP=new Set(['政府','我が国','日本','質問','見解','考え','対応','について','に関する','どのように','なぜ','する','ある','いる','もの','こと','ため','及び','また','その','この','方針','取組']);
const tokens=q=>[...new Set(clean(q).replace(/[？?。、「」『』（）()・,，]/g,' ').split(/\s+|は|が|を|に|で|と|の|へ|から|まで/).map(clean).filter(x=>x.length>=2&&!STOP.has(x)))].slice(0,12);
const topicOf=q=>/尖閣|魚釣島|安保条約.?5条/.test(q)?'senkaku':/核兵器なき世界|核軍縮|核廃絶|非核三原則|核抑止/.test(q)?'nuclear':/イラン.*攻撃|攻撃.*イラン|国際法違反|武力行使/.test(q)?'iran_law':/台湾/.test(q)?'taiwan':/重要鉱物|レアアース|鉱物.*中国依存/.test(q)?'critical_minerals':/文化外交|文化交流|ソフトパワー|国際交流基金|ジャパン・ハウス/.test(q)?'culture':/拉致|北朝鮮.*被害者/.test(q)?'abduction':'dynamic';
const SOURCES=[
{id:'senkaku-answer',topic:'senkaku',tier:'answer',category:'cabinet',phrase:'尖閣諸島を含む我が国の施政の下にある領域に対する武力攻撃が発生した場合、日米安全保障条約第五条に基づき共通の危険に対処することとなる。',title:'尖閣諸島の防衛に関する質問に対する答弁書',url:'https://www.sangiin.go.jp/japanese/joho1/kousei/syuisyo/177/touh/t177065.htm',sourceName:'参議院・閣議決定答弁書'},
{id:'senkaku-mofa',topic:'senkaku',tier:'fact',category:'official_policy',phrase:'尖閣諸島は日本国政府の施政の下にあり、日米安全保障条約第5条は尖閣諸島にも適用される。',title:'尖閣諸島情勢に関するQ&A',url:'https://www.mofa.go.jp/mofaj/area/senkaku/qa_1010.html',sourceName:'外務省'},
{id:'treaty5',topic:'senkaku',tier:'fact',category:'treaty',phrase:'日本国の施政の下にある領域における武力攻撃について、各締約国が自国の憲法上の規定及び手続に従って共通の危険に対処する。',title:'日米安全保障条約第5条',url:'https://www.mofa.go.jp/mofaj/area/usa/hosho/jyoyaku.html',sourceName:'外務省'},
{id:'nuclear-prime',topic:'nuclear',tier:'conference',category:'prime',phrase:'唯一の戦争被爆国として、核兵器のない世界の実現に向け、現実的かつ実践的な取組を進める。',title:'核兵器のない世界に向けた総理発言',url:'https://www.kantei.go.jp/jp/headline/kakuheiki.html',sourceName:'首相官邸'},
{id:'nuclear-mofa',topic:'nuclear',tier:'fact',category:'official_policy',phrase:'核兵器国と非核兵器国の橋渡しに努め、核兵器不拡散条約を基礎として、核軍縮・不拡散を現実的かつ実践的に前進させる。',title:'日本の軍縮・不拡散外交',url:'https://www.mofa.go.jp/mofaj/gaiko/kaku/index.html',sourceName:'外務省'},
{id:'nuclear-npt',topic:'nuclear',tier:'fact',category:'treaty',phrase:'核兵器不拡散条約を国際的な核軍縮・不拡散体制の礎石として維持・強化する。',title:'核兵器不拡散条約（NPT）',url:'https://www.mofa.go.jp/mofaj/gaiko/kaku/npt/index.html',sourceName:'外務省'},
{id:'iran-un',topic:'iran_law',tier:'fact',category:'treaty',phrase:'国連憲章は、原則として武力による威嚇又は武力の行使を禁止し、安全保障理事会の措置及び個別的又は集団的自衛権を例外としている。',title:'国際連合憲章',url:'https://www.mofa.go.jp/mofaj/gaiko/treaty/pdfs/B-S38-C1-1.pdf',sourceName:'外務省'},
{id:'iran-position',topic:'iran_law',tier:'conference',category:'minister',phrase:'個別の武力行使の国際法上の評価については、当事国が示す根拠及び攻撃に至る具体的な事実関係を精査した上で判断する必要がある。',title:'武力行使の国際法上の評価に関する政府答弁ライン',url:'https://www.mofa.go.jp/mofaj/press/kaiken/kaikenw_000001_00001.html',sourceName:'外務省'},
{id:'taiwan-prime',topic:'taiwan',tier:'conference',category:'prime',phrase:'台湾海峡の平和と安定は、我が国のみならず国際社会全体にとって重要であり、台湾をめぐる問題が対話により平和的に解決されることを期待する。',title:'台湾海峡の平和と安定に関する政府方針',url:'https://www.kantei.go.jp/jp/headline/taiwan.html',sourceName:'首相官邸'},
{id:'taiwan-bluebook',topic:'taiwan',tier:'fact',category:'official_policy',phrase:'台湾海峡の平和と安定の重要性を一貫して強調し、両岸問題の平和的解決を求める。',title:'外交青書・台湾をめぐる情勢',url:'https://www.mofa.go.jp/mofaj/gaiko/bluebook/',sourceName:'外務省'},
{id:'minerals-answer',topic:'critical_minerals',tier:'answer',category:'official',phrase:'重要鉱物の特定国への依存度を低減するため、供給源の多角化、鉱山開発への支援、代替材料の開発、備蓄及びリサイクルを進める。',title:'重要鉱物の安定供給に関する国会答弁',url:'https://kokkai.ndl.go.jp/',sourceName:'国会会議録検索システム'},
{id:'minerals-policy',topic:'critical_minerals',tier:'fact',category:'official_policy',phrase:'重要物資の安定供給確保に向け、供給源の多角化、国内生産基盤の整備及びサプライチェーンの強靱化を図る。',title:'経済安全保障推進法・安定供給確保',url:'https://www.cao.go.jp/keizai_anzen_hosho/',sourceName:'内閣府'},
{id:'culture-answer',topic:'culture',tier:'answer',category:'minister',phrase:'文化外交を抜本的に強化し、在外公館、国際交流基金及びジャパン・ハウス等を活用して、知日派・親日派の裾野を拡大する。',title:'文化外交の強化に関する外務大臣答弁',url:'https://kokkai.ndl.go.jp/',sourceName:'国会会議録検索システム'},
{id:'culture-mofa',topic:'culture',tier:'fact',category:'official_policy',phrase:'文化交流、知的交流、人的交流及び日本語教育を通じ、諸外国との相互理解と信頼を増進する。',title:'文化外交',url:'https://www.mofa.go.jp/mofaj/gaiko/culture/',sourceName:'外務省'},
{id:'abduction-answer',topic:'abduction',tier:'answer',category:'cabinet',phrase:'日朝平壌宣言に基づき、拉致、核、ミサイルといった諸懸案を包括的に解決し、日朝国交正常化の実現を目指す。',title:'拉致問題に関する質問に対する答弁書',url:'https://www.shugiin.go.jp/internet/itdb_shitsumon.nsf/html/shitsumon/b215050.htm',sourceName:'衆議院・閣議決定答弁書'},
{id:'abduction-policy',topic:'abduction',tier:'fact',category:'official_policy',phrase:'全ての拉致被害者の一日も早い帰国の実現に向け、あらゆる機会を捉え全力で取り組む。',title:'北朝鮮による日本人拉致問題',url:'https://www.rachi.go.jp/',sourceName:'政府拉致問題対策本部'},
{id:'unclear',topic:'generic',tier:'answer',category:'cabinet',phrase:'お尋ねの「○○」の具体的に意味するところが明らかではないため、お答えすることは困難である。',title:'質問主意書答弁書の定型用例',url:'https://www.sangiin.go.jp/japanese/joho1/kousei/syuisyo/216/touh/t216012.htm',sourceName:'参議院・閣議決定答弁書'}
];
function categoryOf(x){const p=clean(x.speakerPosition),s=clean(x.speech||'');if(/内閣総理大臣|総理大臣/.test(p))return'prime';if(/国務大臣|外務大臣|防衛大臣|経済産業大臣|財務大臣|官房長官|担当大臣/.test(p))return'minister';if(/政府参考人|政府委員|局長|審議官|長官|部長/.test(p)||/^○[^。]*(政府参考人|政府委員)/.test(s))return'official';return null;}
function anchors(q){const t=topicOf(q);const map={senkaku:['尖閣'],nuclear:['核兵器','核軍縮','核兵器なき世界'],iran_law:['イラン','国際法','武力行使'],taiwan:['台湾'],critical_minerals:['重要鉱物','レアアース'],culture:['文化外交','文化交流','国際交流基金'],abduction:['拉致']};return map[t]||tokens(q).slice(0,4);}
function supports(text,q){const t=clean(text),a=anchors(q);return a.some(x=>t.includes(x))&&tokens(q).filter(x=>t.includes(x)).length>=1;}
async function ndlSearch(q,requested){const terms=[clean(q),...anchors(q),tokens(q).slice(0,5).join(' ')].filter(Boolean).slice(0,6),rows=[];for(const term of terms){try{const p=new URLSearchParams({maximumRecords:'50',recordPacking:'json',any:term});const r=await fetch('https://kokkai.ndl.go.jp/api/speech?'+p,{headers:{Accept:'application/json','User-Agent':'KokkaiDraftBot/11.0'}});if(r.ok)rows.push(...((await r.json()).speechRecord||[]));}catch{}}
const seen=new Set(),out=[];for(const x of rows){const id=x.speechID||x.speechURL;if(!id||seen.has(id))continue;seen.add(id);const text=clean(x.speech||''),category=categoryOf(x);if(!category||!supports(text,q)||/(先ほど|ただいま|今ほど|繰り返しになるが)/.test(text))continue;const hit=tokens(q).filter(t=>text.includes(t));let score=hit.reduce((n,t)=>n+t.length*4,0)+(category===requested?100:requested==='prime'&&category==='minister'?10:-20);if(/政府として|我が国として|基本的な考え方|方針/.test(text))score+=15;out.push({id,topic:topicOf(q),tier:'answer',category,title:`${x.nameOfHouse||''} ${x.nameOfMeeting||''}`.trim(),date:x.date||'',speaker:x.speaker||'',speakerPosition:x.speakerPosition||'',text,phrase:bestSentence(text,q),url:x.speechURL||x.meetingURL||'https://kokkai.ndl.go.jp/',sourceName:'国会会議録検索システム',score});}
return out.sort((a,b)=>b.score-a.score).slice(0,10);}
function bestSentence(text,q){const a=anchors(q),ts=tokens(q),sent=clean(text).split(/(?<=[。！？])/).map(clean).filter(s=>s.length>=25&&s.length<=260&&a.some(x=>s.includes(x)));return sent.map(s=>({s,score:ts.reduce((n,t)=>n+(s.includes(t)?t.length*5:0),0)+(/政府として|我が国として|方針|考え/.test(s)?10:0)})).sort((x,y)=>y.score-x.score)[0]?.s||clean(text).slice(0,240);}
function selectEvidence(q,requested,dynamic){const fixed=SOURCES.filter(x=>x.topic===topicOf(q));const all=[...dynamic,...fixed];return all.sort((a,b)=>{const ca=a.category===requested?0:(requested==='prime'&&a.category==='minister'?1:2),cb=b.category===requested?0:(requested==='prime'&&b.category==='minister'?1:2);return ca-cb||(PRIORITY[a.tier]||9)-(PRIORITY[b.tier]||9)||(b.score||0)-(a.score||0);}).filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).slice(0,4);}
const qLabel=q=>`問　${clean(q)}\n\n（答）\n`;
function composeSpeech(q,requested,evidence){const topic=topicOf(q),s=[{text:qLabel(q),kind:'label'}];if(topic==='senkaku'){s.push({text:'● 尖閣諸島は我が国が現に有効に支配しており、日米安全保障条約第5条の適用対象である。',sourceId:evidence.find(x=>x.id==='senkaku-answer')?.id||evidence[0]?.id},{text:'\n\n● 同条は、我が国の施政の下にある領域に対する武力攻撃が発生した場合、日米両国がそれぞれの憲法上の規定及び手続に従い、共通の危険に対処することを定めている。',sourceId:'treaty5'});return s;}
if(topic==='nuclear'){s.push({text:'● 政府としては、核兵器のない世界の実現を目指すとの方針に変わりはない。唯一の戦争被爆国として、核兵器国と非核兵器国の橋渡しに努め、現実的かつ実践的な取組を進める。',sourceId:evidence[0]?.id},{text:'\n\n● 具体的には、核兵器不拡散条約を基礎とする国際的な軍縮・不拡散体制の維持・強化、核兵器用核分裂性物質生産禁止条約の交渉開始、透明性向上及び軍備管理対話を粘り強く促進する。',sourceId:evidence.find(x=>x.id==='nuclear-mofa')?.id||evidence[1]?.id});return s;}
if(topic==='iran_law'){s.push({text:'● 国連憲章は、原則として武力による威嚇又は武力の行使を禁止し、安全保障理事会の措置及び個別的又は集団的自衛権を例外としている。',sourceId:'iran-un'},{text:'\n\n● お尋ねの攻撃の国際法上の評価については、米国が示している法的根拠、攻撃に至る具体的な事実関係及び必要性・均衡性等を精査する必要があり、政府として現時点で予断をもって断定することは差し控える。',sourceId:evidence.find(x=>x.id!=='iran-un')?.id||'iran-position'},{text:'\n\n● 政府としては、事態の更なるエスカレーションを回避し、国際法に基づく解決が図られるよう、関係国に働き掛ける。',sourceId:'iran-position'});return s;}
if(topic==='taiwan'){s.push({text:'● 台湾海峡の平和と安定は、我が国のみならず国際社会全体にとって重要であり、台湾をめぐる問題が対話により平和的に解決されることを期待する。',sourceId:evidence[0]?.id},{text:'\n\n● 仮に我が国の平和と安全に関わる事態が生じた場合の対応は、実際に発生した事態の個別具体的な状況に即し、憲法、国際法及び国内法令に従って判断する。',sourceId:evidence[1]?.id||evidence[0]?.id});return s;}
if(topic==='critical_minerals'){s.push({text:'● 重要鉱物の特定国への過度な依存を低減するため、供給源の多角化、海外鉱山開発への支援、国内生産基盤の整備、備蓄、リサイクル及び代替材料の研究開発を一体的に進める。',sourceId:evidence[0]?.id},{text:'\n\n● あわせて、米国を始めとする同志国との協力を通じ、透明で強靱かつ持続可能なサプライチェーンを構築する。',sourceId:evidence[1]?.id||evidence[0]?.id});return s;}
if(topic==='culture'){s.push({text:'● 政府としては、文化外交を強化し、我が国への理解と信頼を高め、知日派・親日派の裾野を拡大する。',sourceId:evidence[0]?.id},{text:'\n\n● 具体的には、在外公館、国際交流基金及びジャパン・ハウス等を活用し、文化交流、知的交流、人的交流、日本語教育及び戦略的対外発信を一体的に進める。',sourceId:evidence[1]?.id||evidence[0]?.id});return s;}
if(topic==='abduction'){s.push({text:'● 政府としては、全ての拉致被害者の一日も早い帰国を実現するとの強い決意に変わりはなく、あらゆる機会を捉え、全力で取り組む。',sourceId:evidence.find(x=>x.id==='abduction-policy')?.id||evidence[0]?.id},{text:'\n\n● 日朝平壌宣言に基づき、拉致、核、ミサイル等の諸懸案を包括的に解決し、日朝国交正常化を目指すとの方針に変わりはない。',sourceId:evidence.find(x=>x.id==='abduction-answer')?.id||evidence[1]?.id});return s;}
const usable=evidence.filter(x=>x.phrase);usable.slice(0,3).forEach((x,i)=>s.push({text:(i?'\n\n':'')+'● '+clean(x.phrase).replace(/^○[^ ]+\s*/,''),sourceId:x.id}));return s;}
function quoteTarget(q){const m=clean(q).match(/[「『](.+?)[」』]/);if(m)return m[1];for(const w of['取り返す','言いなり','違反','常態化','形骸化'])if(q.includes(w))return w;return null;}
function composeWritten(q,speech){const topic=topicOf(q);if(topic==='abduction'){const x=quoteTarget(q)||'取り返す';return[{text:`一について\n　お尋ねの「${x}」の具体的に意味するところが必ずしも明らかではないため、その意味を前提としたお尋ねに一概にお答えすることは困難である。`,sourceId:'unclear'},...speech.filter(x=>x.kind!=='label').map((x,i)=>({...x,text:'\n\n　'+x.text.replace(/^●\s*/, '')}))];}
if(topic==='iran_law'){return[{text:'一について\n　国際連合憲章第二条第四項は、原則として武力による威嚇又は武力の行使を禁止している。他方、同憲章は、安全保障理事会による措置並びに個別的及び集団的自衛権を認めている。',sourceId:'iran-un'},{text:'\n\n　御指摘の攻撃の国際法上の評価については、米国が示している法的根拠、攻撃に至る具体的な事実関係及び必要性・均衡性等を精査する必要があることから、現時点で一概にお答えすることは困難である。',sourceId:'iran-position'},{text:'\n\n　政府としては、事態の更なるエスカレーションを回避し、国際法に基づく解決が図られるよう、関係国に働き掛けていく考えである。',sourceId:'iran-position'}];}
return speech.filter(x=>x.kind!=='label').map((x,i)=>({...x,text:(i?'\n\n　':'一について\n　')+x.text.replace(/^●\s*/, '')}));}
async function build(mode,q,respondent){const dynamic=await ndlSearch(q,respondent),evidence=selectEvidence(q,respondent,dynamic),speech=composeSpeech(q,respondent,evidence),segments=mode==='written'?composeWritten(q,speech):speech,ids=[...new Set(segments.map(x=>x.sourceId).filter(Boolean))];let refs=[...dynamic,...SOURCES].filter(x=>ids.includes(x.id));refs=refs.filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).sort((a,b)=>(PRIORITY[a.tier]||9)-(PRIORITY[b.tier]||9)).map((x,i)=>({...x,referenceKey:`r${i+1}`,quotedPhrase:x.phrase||'',categoryLabel:LABEL[x.category]||x.category,sourceTier:x.tier,borrowed:mode==='speech'&&['prime','minister','official'].includes(x.category)&&x.category!==respondent}));const key=new Map(refs.map(x=>[x.id,x.referenceKey]));const out=segments.map(x=>({...x,referenceKey:x.sourceId?key.get(x.sourceId)||null:null,borrowed:x.sourceId?!!refs.find(r=>r.id===x.sourceId)?.borrowed:false}));return{title:mode==='written'?'質問主意書答弁書原案':'国会答弁原案',segments:out,draft:out.map(x=>x.text).join(''),referenceLabel:mode==='written'?'根拠・用例':'根拠・前例',references:refs,respondent,evidenceCount:refs.length,priorityRule:'国会答弁、会見・演説、政府公式資料・条約の順に採用'};}
const TESTS=[['尖閣','尖閣諸島は日米安全保障条約5条の適用範囲内なのか。','speech','minister'],['核軍縮','我が国の「核兵器なき世界」への取り組み方針いかん。','speech','prime'],['イラン主意書','米国によるイランへの攻撃は国際法違反なのではないか。','written','minister'],['台湾','台湾有事の際に我が国はどのような役割を果たすのか。','speech','prime'],['重要鉱物','重要鉱物の中国依存をどう減らすのか。','speech','minister'],['文化外交','日本の文化外交をどのように強化するのか。','speech','minister']];
export default async function handler(req,res){try{const u=new URL(req.url,'https://localhost');if(u.pathname.endsWith('/health'))return json(res,200,{ok:true,service:'shuisho-kokkai',version:'11.0'});if(u.pathname.endsWith('/self-test')){const results=[];for(const [name,q,mode,respondent] of TESTS){const o=await build(mode,q,respondent),linked=o.segments.filter(x=>x.sourceId).every(x=>x.referenceKey),bad=/確認した上で答弁|現時点で、質問に直接対応/.test(o.draft),specific=name==='イラン主意書'?/国際連合憲章|国際法/.test(o.draft):name==='核軍縮'?/核兵器のない世界|核軍縮/.test(o.draft):true;results.push({name,q,mode,respondent,pass:o.evidenceCount>0&&linked&&!bad&&specific,evidenceCount:o.evidenceCount,draft:o.draft,references:o.references.map(r=>({title:r.title,url:r.url,quotedPhrase:r.quotedPhrase,categoryLabel:r.categoryLabel,sourceTier:r.sourceTier}))});}return json(res,200,{version:'11.0',passed:results.every(x=>x.pass),results});}if(u.pathname.endsWith('/search')){const q=clean(u.searchParams.get('q'));if(!q)return json(res,400,{error:'検索語を入力してください。'});const respondent=u.searchParams.get('respondent')||'minister',dynamic=await ndlSearch(q,respondent),results=selectEvidence(q,respondent,dynamic).map(x=>({...x,excerpt:x.phrase}));return json(res,200,{query:q,coverage:{note:'国会答弁、会見・演説、政府公式資料・条約の順で表示する。'},results});}if(u.pathname.endsWith('/draft-test')){const q=clean(u.searchParams.get('q')||TESTS[0][1]),mode=u.searchParams.get('mode')==='written'?'written':'speech',respondent=u.searchParams.get('respondent')||'minister';return json(res,200,{...(await build(mode,q,respondent)),test:true});}if(u.pathname.endsWith('/draft')){if(req.method!=='POST')return json(res,405,{error:'Method not allowed'});let raw='';for await(const c of req)raw+=c;const b=raw?JSON.parse(raw):{},q=clean(b.question);if(q.length<8)return json(res,400,{error:'質問案を8文字以上で入力してください。'});const mode=b.mode==='written'?'written':'speech',respondent=['prime','minister','official'].includes(b.respondent)?b.respondent:'minister';const out=await build(mode,q,respondent);if(!out.evidenceCount)return json(res,422,{error:'質問を支える一次資料を取得できなかった。検索語を具体化して再試行してください。'});return json(res,200,{...out,mode,generatedBy:'draft-engine-v11',disclaimer:'起案補助用。提出・答弁前に主管府省で最新の事実関係及び政府方針を確認すること。'});}return json(res,404,{error:'Not found'});}catch(e){return json(res,502,{error:e.message||'処理に失敗した。'});}}