const json=(r,s,b)=>{r.statusCode=s;r.setHeader('Content-Type','application/json; charset=utf-8');r.setHeader('Cache-Control','no-store, max-age=0');r.end(JSON.stringify(b));};
const clean=s=>String(s||'').replace(/<[^>]+>/g,' ').replace(/^○[^\s　]+[\s　]*/,'').replace(/\s+/g,' ').trim();
const LABEL={prime:'総理',minister:'大臣',official:'政府参考人',cabinet:'閣議決定済み答弁書',official_policy:'政府公式資料',treaty:'条約・国際文書'};
const STOP=new Set(['政府','我が国','日本','見解','質問','答弁','考え','対応','取組','取り組み','方針','いかん','なのか','ではないか','どのように','について','に関する','する','ある','いる','もの','こと','ため','及び','また','その','この','いずれも']);
const intentWords=/適用|対象|領土|帰属|違反|評価|認識|理由|措置|支援|強化|削減|実現|役割|影響|対応|方針|事実|有無|可能|必要|十分|責任/;
const sourcePriority={answer:0,press:1,fact:2,generated:3};
const STATIC=[
{id:'senkaku-position',keys:['尖閣諸島'],sourceType:'answer',category:'cabinet',phrase:'尖閣諸島は、歴史的にも国際法上も疑いのない我が国固有の領土であり、現に我が国はこれを有効に支配している。',title:'尖閣諸島に関する政府の基本的見解',url:'https://www.mofa.go.jp/mofaj/area/senkaku/',sourceName:'外務省'},
{id:'takeshima-position',keys:['竹島'],sourceType:'answer',category:'official_policy',phrase:'竹島は、歴史的事実に照らしても、かつ国際法上も明らかに我が国固有の領土である。韓国による竹島の占拠は、国際法上何ら根拠がないまま行われている不法占拠である。',title:'竹島問題に関する政府の基本的立場',url:'https://www.mofa.go.jp/mofaj/area/takeshima/',sourceName:'外務省'},
{id:'northern-position',keys:['北方領土','北方四島'],sourceType:'answer',category:'official_policy',phrase:'北方四島は我が国固有の領土であるが、現在ロシアに不法占拠されている。政府は、北方四島の帰属の問題を解決して平和条約を締結するとの基本方針を堅持している。',title:'北方領土問題に関する政府の基本的立場',url:'https://www.mofa.go.jp/mofaj/area/hoppo/',sourceName:'外務省'},
{id:'treaty5',keys:['日米安全保障条約第5条','安保条約5条'],sourceType:'fact',category:'treaty',phrase:'日本国の施政の下にある領域における武力攻撃について、各締約国が自国の憲法上の規定及び手続に従って共通の危険に対処する。',title:'日米安全保障条約第5条',url:'https://www.mofa.go.jp/mofaj/area/usa/hosho/jyoyaku.html',sourceName:'外務省'},
{id:'abduction-answer',keys:['拉致','拉致被害者'],sourceType:'answer',category:'cabinet',phrase:'日朝平壌宣言に基づき、拉致、核、ミサイルといった諸懸案を包括的に解決し、日朝国交正常化の実現を目指す。',title:'拉致問題に関する質問に対する答弁書',url:'https://www.shugiin.go.jp/internet/itdb_shitsumon.nsf/html/shitsumon/b215050.htm',sourceName:'衆議院・閣議決定答弁書'},
{id:'abduction-policy',keys:['拉致','拉致被害者'],sourceType:'fact',category:'official_policy',phrase:'全ての拉致被害者の一日も早い帰国の実現に向け、あらゆる機会を捉え全力で取り組む。',title:'北朝鮮による日本人拉致問題',url:'https://www.rachi.go.jp/',sourceName:'政府拉致問題対策本部'},
{id:'nuclear-prime',keys:['核兵器なき世界','核兵器のない世界','核軍縮'],sourceType:'press',category:'prime',phrase:'唯一の戦争被爆国として、核兵器のない世界の実現に向け、現実的かつ実践的な取組を進める。',title:'核兵器のない世界に向けた総理発言',url:'https://www.kantei.go.jp/jp/headline/kakuheiki.html',sourceName:'首相官邸'},
{id:'nuclear-policy',keys:['核兵器なき世界','核兵器のない世界','核軍縮'],sourceType:'fact',category:'official_policy',phrase:'核兵器国と非核兵器国の橋渡しに努め、核兵器不拡散条約を基礎として、核軍縮・不拡散を現実的かつ実践的に前進させる。',title:'日本の軍縮・不拡散外交',url:'https://www.mofa.go.jp/mofaj/gaiko/kaku/index.html',sourceName:'外務省'},
{id:'culture-policy',keys:['文化外交','文化交流','ソフトパワー'],sourceType:'fact',category:'official_policy',phrase:'在外公館、国際交流基金及びジャパン・ハウス等を活用し、文化交流、知的交流、人的交流及び日本語教育を推進する。',title:'文化外交',url:'https://www.mofa.go.jp/mofaj/gaiko/culture/',sourceName:'外務省'},
{id:'un-charter',keys:['国際法違反','武力行使','攻撃'],sourceType:'fact',category:'treaty',phrase:'国際連合憲章第二条第四項は武力による威嚇又は武力の行使を原則として禁止し、同憲章は安全保障理事会の措置並びに個別的及び集団的自衛権を認めている。',title:'国際連合憲章',url:'https://www.mofa.go.jp/mofaj/gaiko/treaty/pdfs/B-S38-C1-1.pdf',sourceName:'外務省'},
{id:'unclear',keys:[],sourceType:'answer',category:'cabinet',phrase:'お尋ねの「○○」の具体的に意味するところが明らかではないため、お答えすることは困難である。',title:'質問主意書答弁書の定型用例',url:'https://www.sangiin.go.jp/japanese/joho1/kousei/syuisyo/216/touh/t216012.htm',sourceName:'参議院・閣議決定答弁書'}
];
const words=s=>[...new Set(clean(s).replace(/[？?。、「」『』（）()・,，]/g,' ').split(/\s+|は|が|を|に|で|と|の|へ|から|まで|及び|並びに|又は/).map(clean).filter(x=>x.length>=2&&!STOP.has(x)))];
function splitIssues(q){const text=clean(q),parts=text.split(/[、,，]|及び|並びに|ならびに|または|又は/).map(clean).filter(Boolean);if(parts.length<=1)return[{label:text,query:text,anchors:words(text).slice(0,5)}];const tail=parts[parts.length-1],intent=(tail.match(/(?:は|について)?([^。？?]{0,32}(?:なのか|ではないか|いかん|説明されたい|問う|示されたい))/?[1]:'');return parts.map((p,i)=>{let label=p.replace(/^(問|政府は|我が国は)/,'').replace(/(は|について)?[^。]{0,30}(なのか|ではないか|いかん|問う)$/,'').trim();if(i===parts.length-1&&intent)label=p.replace(intent,'').replace(/[は、 ]+$/,'').trim();return{label:label||p,query:(label||p)+(intent||''),anchors:words(label||p).slice(0,4)}}).filter(x=>x.anchors.length||x.label.length>=2);}
function categoryOf(x){const p=clean(x.speakerPosition),s=clean(x.speech);if(/内閣総理大臣|総理大臣/.test(p))return'prime';if(/国務大臣|外務大臣|防衛大臣|経済産業大臣|財務大臣|官房長官|担当大臣/.test(p))return'minister';if(/政府参考人|政府委員|局長|審議官|長官|部長/.test(p)||/^○[^。]*(政府参考人|政府委員)/.test(s))return'official';return null;}
const sentences=t=>clean(t).split(/(?<=[。！？])/).map(clean).filter(s=>s.length>=18&&s.length<=280);
function relevance(text,issue){const t=clean(text),hits=issue.anchors.filter(a=>t.includes(a));return hits.reduce((n,a)=>n+a.length*6,0)+(intentWords.test(t)?12:0)+(hits.length===issue.anchors.length&&hits.length?25:0);}
function bestPassage(text,issue){const ss=sentences(text),scored=ss.map((s,i)=>({s,i,v:relevance(s,issue)+(i<2?4:0)})).filter(x=>x.v>0).sort((a,b)=>b.v-a.v);if(!scored.length)return'';const a=scored[0],next=ss[a.i+1];return next&&relevance(next,issue)>5&&a.s.length+next.length<360?a.s+next:a.s;}
async function ndl(issue,respondent){const terms=[issue.query,...issue.anchors,issue.anchors.join(' ')].filter(Boolean).slice(0,6),all=[];for(const term of terms){try{const p=new URLSearchParams({maximumRecords:'50',recordPacking:'json',any:term});const f=await fetch('https://kokkai.ndl.go.jp/api/speech?'+p,{headers:{Accept:'application/json','User-Agent':'KokkaiDraftBot/12.0'}});if(f.ok)all.push(...((await f.json()).speechRecord||[]));}catch{}}
const seen=new Set(),out=[];for(const x of all){const id=x.speechID||x.speechURL;if(!id||seen.has(id))continue;seen.add(id);const category=categoryOf(x),text=clean(x.speech);if(!category||/先ほど|ただいま|今申し上げた|御指摘のとおり/.test(text))continue;const passage=bestPassage(text,issue),rel=relevance(passage,issue);if(!passage||rel<18)continue;const cat=category===respondent?80:respondent==='prime'&&category==='minister'?15:0;out.push({id,sourceType:'answer',category,phrase:passage,title:`${x.nameOfHouse||''} ${x.nameOfMeeting||''}`.trim(),url:x.speechURL||x.meetingURL||'https://kokkai.ndl.go.jp/',sourceName:'国会会議録検索システム',date:x.date||'',speaker:x.speaker||'',speakerPosition:x.speakerPosition||'',score:rel+cat});}
return out.sort((a,b)=>b.score-a.score).slice(0,8);}
function staticFor(issue){return STATIC.filter(s=>s.keys.some(k=>issue.query.includes(k)||issue.label.includes(k)||issue.anchors.some(a=>k.includes(a)||a.includes(k)))).map(s=>({...s,score:relevance(s.phrase,issue)+45})).filter(s=>s.score>=45);}
function answersQuestion(src,issue){const p=src.phrase;return relevance(p,issue)>=24&&(intentWords.test(p)||/である|ではない|目指す|取り組む|認められない|不法占拠|有効に支配/.test(p));}
function selectEvidence(candidates,issue,respondent){const sorted=[...candidates].sort((a,b)=>sourcePriority[a.sourceType]-sourcePriority[b.sourceType]||((a.category===respondent)?-1:1)||b.score-a.score);const first=sorted.find(x=>x.sourceType==='answer'&&answersQuestion(x,issue))||sorted[0];if(!first)return[];if(answersQuestion(first,issue))return[first];const supplement=sorted.find(x=>x.id!==first.id&&answersQuestion(x,issue));return supplement?[first,supplement]:[first];}
function minimalGenerate(issue,source){const anchor=issue.label;return source?`${anchor}については、${source.phrase.replace(/。$/,'')}。`:`${anchor}については、政府として、関係する事実関係及び法的枠組みを踏まえ、我が国の国益の観点から適切に対応する。`;}
async function draftIssue(issue,respondent){const dynamic=await ndl(issue,respondent),statics=staticFor(issue),picked=selectEvidence([...dynamic,...statics],issue,respondent);if(!picked.length)return{segments:[{text:'● '+minimalGenerate(issue,null),generated:true}],refs:[]};const primary=picked[0];let text=primary.phrase;if(!answersQuestion(primary,issue))text=minimalGenerate(issue,primary);return{segments:[{text:'● '+text,sourceId:primary.id},...picked.slice(1).map(x=>({text:'\n\n● '+x.phrase,sourceId:x.id}))],refs:picked};}
function target(q){const m=clean(q).match(/[「『](.+?)[」』]/);return m?.[1]||null;}
async function build(mode,q,respondent){const issues=splitIssues(q),allSeg=[],allRefs=[];for(const issue of issues){const d=await draftIssue(issue,respondent);allSeg.push(...d.segments);allRefs.push(...d.refs);}let segments;if(mode==='written'){segments=allSeg.map((x,i)=>({...x,text:(i?'\n\n　':'一について\n　')+x.text.replace(/^●\s*/, '')}));const t=target(q);if(t&&/意味|定義|指す|いう/.test(q)){segments.unshift({text:`一について\n　お尋ねの「${t}」の具体的に意味するところが明らかではないため、その意味を前提としたお尋ねに一概にお答えすることは困難である。`,sourceId:'unclear'});allRefs.push(STATIC.find(x=>x.id==='unclear'));}}else segments=[{text:`問　${clean(q)}\n\n（答）\n`,kind:'label'},...allSeg.map((x,i)=>({...x,text:(i?'\n\n':'')+x.text}))];
let refs=allRefs.filter(Boolean).filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i);refs.sort((a,b)=>sourcePriority[a.sourceType]-sourcePriority[b.sourceType]);refs=refs.map((x,i)=>({...x,referenceKey:`r${i+1}`,quotedPhrase:x.phrase,categoryLabel:LABEL[x.category]||x.category,sourceTypeLabel:{answer:'国会答弁・答弁書',press:'会見・演説',fact:'政府公式資料・条約'}[x.sourceType]||x.sourceType,borrowed:['prime','minister','official'].includes(x.category)&&x.category!==respondent}));const key=new Map(refs.map(x=>[x.id,x.referenceKey]));segments=segments.map(x=>({...x,referenceKey:x.sourceId?key.get(x.sourceId)||null:null,borrowed:x.sourceId?!!refs.find(r=>r.id===x.sourceId)?.borrowed:false}));return{title:mode==='written'?'質問主意書答弁書原案':'国会答弁原案',segments,draft:segments.map(x=>x.text).join(''),references:refs,referenceLabel:mode==='written'?'根拠・用例':'根拠・前例',respondent,evidenceCount:refs.length,issues:issues.map(x=>x.label),priorityRule:'同一答弁者の過去答弁を継承し、不足時のみ会見・公式資料・最小限生成で補完'};}
const TESTS=[['複数領土','尖閣諸島、竹島、北方領土はいずれも日本のものなのではないか。','speech','minister',['尖閣','竹島','北方']],['核軍縮','我が国の「核兵器なき世界」への取り組み方針いかん。','speech','prime',['核兵器']],['拉致','政府は拉致被害者を取り返す気があるのか。','written','minister',['拉致']]];
export default async function handler(req,res){try{const u=new URL(req.url,'https://localhost');if(u.pathname.endsWith('/health'))return json(res,200,{ok:true,version:'12.0'});if(u.pathname.endsWith('/self-test')){const results=[];for(const [name,q,m,p,need] of TESTS){const o=await build(m,q,p),covered=need.every(k=>o.draft.includes(k)),linked=o.segments.filter(x=>x.sourceId).every(x=>x.referenceKey);results.push({name,pass:covered&&linked&&o.evidenceCount>0,covered,issues:o.issues,evidenceCount:o.evidenceCount,draft:o.draft,references:o.references});}return json(res,200,{version:'12.0',passed:results.every(x=>x.pass),results});}if(u.pathname.endsWith('/draft-test')){const q=clean(u.searchParams.get('q')||TESTS[0][1]),m=u.searchParams.get('mode')==='written'?'written':'speech',p=u.searchParams.get('respondent')||'minister';return json(res,200,{...(await build(m,q,p)),test:true});}if(u.pathname.endsWith('/search')){const q=clean(u.searchParams.get('q')),p=u.searchParams.get('respondent')||'minister',issues=splitIssues(q),results=[];for(const issue of issues)results.push(...await ndl(issue,p),...staticFor(issue));return json(res,200,{query:q,coverage:{note:'過去答弁を最優先し、会見・公式資料の順に表示する。'},results:results.filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).sort((a,b)=>sourcePriority[a.sourceType]-sourcePriority[b.sourceType]||b.score-a.score)});}if(u.pathname.endsWith('/draft')){if(req.method!=='POST')return json(res,405,{error:'Method not allowed'});let raw='';for await(const c of req)raw+=c;const b=raw?JSON.parse(raw):{},q=clean(b.question),m=b.mode==='written'?'written':'speech',p=['prime','minister','official'].includes(b.respondent)?b.respondent:'minister';if(q.length<8)return json(res,400,{error:'質問を8文字以上で入力してください。'});const o=await build(m,q,p);return json(res,200,{...o,mode:m,generatedBy:'draft-engine-v12',disclaimer:'起案補助用。提出・答弁前に主管府省で最新の事実関係及び政府方針を確認すること。'});}return json(res,404,{error:'Not found'});}catch(e){return json(res,502,{error:e.message||'処理に失敗した。'});}}